=== provenance-io/provwasm/packages/bindings/schema/scope.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Scope",
  "description": "Defines a root reference for a collection of records owned by one or more parties.",
  "type": "object",
  "required": [
    "scope_id",
    "specification_id",
    "value_owner_address"
  ],
  "properties": {
    "data_access": {
      "default": [],
      "type": "array",
      "items": {
        "$ref": "#/definitions/Addr"
      }
    },
    "owners": {
      "default": [],
      "type": "array",
      "items": {
        "$ref": "#/definitions/Party"
      }
    },
    "scope_id": {
      "$ref": "#/definitions/Addr"
    },
    "specification_id": {
      "$ref": "#/definitions/Addr"
    },
    "value_owner_address": {
      "type": "string"
    }
  },
  "definitions": {
    "Addr": {
      "description": "A human readable address.\n\nIn Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.\n\nThis type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.\n\nThis type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.",
      "type": "string"
    },
    "Party": {
      "description": "An address with an associated role.",
      "type": "object",
      "required": [
        "address",
        "role"
      ],
      "properties": {
        "address": {
          "$ref": "#/definitions/Addr"
        },
        "role": {
          "$ref": "#/definitions/PartyType"
        }
      }
    },
    "PartyType": {
      "description": "Defines roles that can be associated to a party.",
      "type": "string",
      "enum": [
        "originator",
        "servicer",
        "investor",
        "custodian",
        "owner",
        "affiliate",
        "omnibus",
        "provenance",
        "unspecified"
      ]
    }
  }
}

=== provenance-io/provwasm/packages/provwasm-mocks/testdata/scope.json
{
    "scope_id": "scope1qqqqq2wf3c4yt4u447m8pw65qcdqrre82d",
    "specification_id": "scopespec1qj5hx4l3vgryhp5g3ks68wh53jkq3net7n",
    "owners": [
        {
            "address": "tp1rr4d0eu62pgt4edw38d2ev27798pfhdhp5ttha",
            "role": "originator"
        }
    ],
    "data_access": [
        "tp1rr4d0eu62pgt4edw38d2ev27798pfhdhp5ttha"
    ],
    "value_owner_address": "tp1r7dd2w80x939u5f3l5y04rruusyr5dxx7wuvdm"
}
